### ISSUE TITLE
downloading issues

### ISSUE THREAD

**Issue by luvjOi** [griffenx/Apex-Launcher#18]
Hi, I've been having some real trouble trying to just download the game and start playing it since yesterday. I tried both the launcher and the manual downloads. Downloading the game via the launcher was slower than the manual one. and I don't remember it given me any error message, just that nothing seemed to happen after I downloaded. The patch download worked after some time but downloading the game afterwards didn't seem to work. If I remember correctly it would just ask again to download the game. The manual does dive some kind of error when I try to extract the file from the zipped folder but I don't think it'll help any. All it says is "Data error Game.rgssad" 

I have a Window 7 pc laptop, Intel if that also helps any. Thanks, this is my first time trying to download the game as I only heard about it the other day and the whole thing just interested me. Thanks for the help!

**Comment by griffenx** [comment]
This sounds to me like an issue with your internet connection. The base version of each build will definitely take a little while to download, since it's about 700MB. If you have a poor download speed (~400kB/s), it will take about 30 minutes to download. Try doing a speed test on a site like [speedtest.net](speedtest.net) and see what you're getting for your download speed.

The files themselves are hosted on Mediafire, so I'm fairly confident that this isn't an issue with the files themselves. Plus since this seems to be happening both in and out of the Launcher indicates to me that this isn't a Launcher issue.

I'm going to go ahead and mark this as a Non-Issue for now.

**Comment by luvjOi** [comment]
You were right it was my internet connection. It works now, got the game downloaded!

-Tezca

**Comment by griffenx** [comment]
Glad to hear it. Enjoy!
