### ISSUE TITLE
Apex Launcher Hangs

### ISSUE THREAD

**Issue by Craxuan** [griffenx/Apex-Launcher#5]
The situation is like this. I've previously downloaded the Build 4 before, and I redownloaded and opened the launcher. The first thing it says is,

![image](https://cloud.githubusercontent.com/assets/20674130/17200966/7c2fd90e-54bc-11e6-86da-5a43804d513f.png)

In my settings I've already set the install path - or it auto detects, I'm not sure which - to the Build 4 game folder. In my head, I believe the launcher should auto detect the game and not pop up a request for new update. Note that I did a manual download of the game earlier due to the launcher issue, so maybe the launcher downloaded game and manually downloaded game has minor differences? Here as seen:

![image](https://cloud.githubusercontent.com/assets/20674130/17201050/46585c2e-54bd-11e6-9ce8-0f2bdd555dcf.png)

![image](https://cloud.githubusercontent.com/assets/20674130/17201074/78f54796-54bd-11e6-8e89-54c48e60eb01.png)

If I click to download, it hangs, the usual 'window not responding' and stuff. I'm not sure if it's because it's downloading the game or it's the usual freeze.

**Comment by griffenx** [comment]
The version number is messed up from when you had issues with the launcher before. It's easy to change by going into the program's `config.txt` file and changing the version to `ALPHA 3.2` or whatever. Since you had it download the most recent version, though, it's downloading Build 4 and would correct itself anyway.

As for the main issue, the reason the program hangs is because the .zip file for Build 4 is over 350 MB in size and the method it's using to download the file is a really simple one that just locks up the thread until it finishes. Basically, the file is still downloading and the program is waiting on the file to download before continuing. Once the file finishes, it should (in theory) unblock and run normally.

As I mentioned on Discord, in the future, I'm planning on having a background thread for downloading the game, so that will avoid locking up the program.

**Comment by Jdoge77** [comment]
Yes I have had the same problem, however I left the launcher open for 2.5 days and it constantly said extracting version 4 and never gave any indication of finishing.  I am not trying to bother you, just letting you know I have a problem with it and I am very grateful for the time and effort you put into making this whole project.  Thank you.

**Comment by griffenx** [comment]
This should be fixed in the next version. The new downloading system is working pretty well, I just need to put the finishing touches on it before I release it to everyone.

**Comment by griffenx** [comment]
This should now be fixed in the latest release. Let me know if the issue persists, otherwise I'll be marking this as solved.

**Comment by griffenx** [comment]
Since I have not been notified of continuing issue, I'm gonna go ahead and close this issue.
